{
 "title": "GNSS overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Received Data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(receive_time,1m),\n  mountpoint AS metric,\n  sum(rtcm_msg_size) AS \"rtcm_msg_size\"\nFROM rtcm_packages\nWHERE\n  $__timeFilter(receive_time)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average satellite count per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n$__timeGroupAlias(receive_time,1m),\r\nmountpoint AS metric,\r\n SUM(rtcm_sat_count)/60 AS rtcm_sat_count\r\n FROM rtcm_packages\r\n WHERE\r\n   $__timeFilter(receive_time)\r\n   GROUP BY 1,2\r\n   ORDER BY 1,2\r\n"
    }
   ]
  },
  {
   "title": "Average SNR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(obs_epoch,1m),\n  mountpoint AS metric,\n  avg(obs_snr) AS \"avg_snr\"\nFROM gps_observations\nWHERE\n  $__timeFilter(obs_epoch)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Cycle slips",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(obs_epoch,1m),\n  mountpoint AS metric,\n  count(obs_lock_time_indicator) AS \"obs_lock_time_indicator\"\nFROM gps_observations\nWHERE\n  $__timeFilter(obs_epoch) AND\n  obs_lock_time_indicator < 1\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}